### ISSUE TITLE
autolayout collapses on iPad

### ISSUE THREAD

**Issue by Tacha-S** [plenprojectcompany/plen-Scenography_iOS#5]

**Comment by trevinwisaksana** [comment]
I attempted to fix the auto layout for the iPad. However, I have to resize the joystick. Would this be acceptable? 
![adjusted ipad autolayout](https://cloud.githubusercontent.com/assets/20000813/25163918/72f5f332-2482-11e7-958d-4a7896d87f77.png)

**Comment by Tacha-S** [comment]
Thanks!!:laughing:

I feel better that the joystick field is same in both the width and height.
In addition to the fix, how about fitting the height to the width?

**Comment by trevinwisaksana** [comment]
Sure, I can do that 👍🏼

**Comment by trevinwisaksana** [comment]
![updated auto layout ipad](https://cloud.githubusercontent.com/assets/20000813/25164775/ff67d182-2487-11e7-957b-b4b2d9f20787.png)

How about this?

**Comment by Tacha-S** [comment]
![](http://i.imgur.com/lkr8ntR.jpg)
