### ISSUE TITLE
Last four items on every PlenMotionTableViewController are the same and has no image

### ISSUE THREAD

**Issue by trevinwisaksana** [plenprojectcompany/plen-Scenography_iOS#9]
![issue](https://cloud.githubusercontent.com/assets/20000813/26253777/afc0c73c-3cde-11e7-8185-8dd78cefc09a.png)

**Comment by trevinwisaksana** [comment]
Currently fixing this issue.

**Comment by Tacha-S** [comment]
This issue related with PR #8.
Normal, Soccer and Dance was added by #8.

**Comment by trevinwisaksana** [comment]
I see, I will close this issue.
